\documentclass[]{book}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdftitle={SEM and R},
            pdfauthor={Bill},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{natbib}
\bibliographystyle{apalike}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\providecommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{SEM and R}
    \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
    \author{Bill}
    \preauthor{\centering\large\emph}
  \postauthor{\par}
      \predate{\centering\large\emph}
  \postdate{\par}
    \date{2021-05-02}

\usepackage{booktabs}
\usepackage{amsthm}
\makeatletter
\def\thm@space@setup{%
  \thm@preskip=8pt plus 2pt minus 4pt
  \thm@postskip=\thm@preskip
}
\makeatother

\begin{document}
\maketitle

{
\setcounter{tocdepth}{1}
\tableofcontents
}
\hypertarget{sem-and-r}{%
\chapter{SEM and R}\label{sem-and-r}}

This is the starting point.

\hypertarget{intro}{%
\chapter{Introduction}\label{intro}}

The following R codes and texts are from UCLA website ``\url{https://stats.idre.ucla.edu/r/seminars/rsem/}'' and I do not own the copyright of the R codes or texts. I wrote this R Markdown file for my own study purpose.

\textbf{Given this consideration, please do NOT distribute this page in any way.}

\hypertarget{definitions-basic-concepts}{%
\section{Definitions (Basic Concepts)}\label{definitions-basic-concepts}}

\hypertarget{observed-variable}{%
\subsection{Observed variable}\label{observed-variable}}

Observed variable: A variable that exists in the data (a.k.a item or manifest variable)

\hypertarget{latent-variable}{%
\subsection{Latent variable}\label{latent-variable}}

Latent variable: A variable that is constructed and does not exist in the data.

\hypertarget{exogenous-variable}{%
\subsection{Exogenous variable}\label{exogenous-variable}}

Exogenous variable: An independent variable either observed (X) or latent (\(\xi\)) that explains an engogenous variable.

\hypertarget{endogenous-variable}{%
\subsection{Endogenous variable}\label{endogenous-variable}}

Endogenous variable: A dependent variable, either observed (Y) or latent (\(\eta\)) that has a causal path leading to it.

\hypertarget{measurement-model}{%
\subsection{Measurement model}\label{measurement-model}}

Measurement model: A model that links obseved variables with latent variables.

\hypertarget{indicator-in-a-measurement-model}{%
\subsection{Indicator (in a measurement model)}\label{indicator-in-a-measurement-model}}

Indicator: An observed variable in a measurement model (can be exogenous or endogenous).

\hypertarget{factor}{%
\subsection{Factor}\label{factor}}

Factor: A latent variable defined by its indicators (can be exogenous or endogeous).

\hypertarget{loading}{%
\subsection{Loading}\label{loading}}

Loading: A path between an indicator and a factor.

\hypertarget{structural-model}{%
\subsection{Structural model}\label{structural-model}}

Structural model: A model that specifies casual relationships among exogeous variables to endogeous variables (can be observed or latent).

\hypertarget{regerssion-path}{%
\subsection{Regerssion path}\label{regerssion-path}}

Regression path: A path between exogeous and endogeous variables (can be observed or latent).

\hypertarget{the-path-diagram}{%
\section{The path diagram}\label{the-path-diagram}}

Circles represent latent variables. Squares represent observed indicators. Triangles represent intercepts or means. One way arrows represent paths. Two-way arrows represent either variances or covariances.

\hypertarget{lavaan-syntax}{%
\section{Lavaan syntax}\label{lavaan-syntax}}

\(\sim\) \textbf{predict}: used for regression of observed outcome to observed predictors (e.g., \(y \sim x\)).

\(= \sim\) \textbf{indicator}: used for latent variable to observed indicator in factor analysis measurement models (e.g., \(f= \sim q+r+s\)).

\(\sim \sim\) \textbf{covariance}: (e.g., \(x \sim \sim x\)).

\(\sim 1\) \textbf{intercept or mean}: (e.g., \(x \sim 1\) estimates the mean of variable \(x\)).

\(1*\) \textbf{fixes parameter or loading to one}: (e.g., \(f =\sim 1*q\)).

\(NA *\) \textbf{free parameter or loading}: used to override default marker method (e.g., \(f=\sim NA * q\)).

\(a*\) \textbf{lables the parameter `a'}: used for model constraints (e.g., \(f=\sim a*q\)).

\hypertarget{regression-and-path-analysis}{%
\section{Regression and path analysis}\label{regression-and-path-analysis}}

\[y_{1}=b_{0}+b_{1}x_{1}+\epsilon_{1}\]
\[y_{1}=\alpha+\gamma_{1} x_{1}+\zeta_{1}\]

\(x_{1}\) single exogenous variable

\(y_{1}\) single endogenous variable

\(b_{0}\), \(\alpha_{1}\) intercept of \(y_{1}\) (alpha)

\(b_{1}\), \(\gamma_{1}\) regression coefficient (gamma)

\(\epsilon_{1}\), \(\zeta_{1}\) residual of \(y_{1}\) (epsilon, zeta)

\(\phi\) variance or covariance of the exogenous variable (phi)

\(\psi\) residual variance or covariance of the endogenous variable (psi)

\hypertarget{real-data-example-simple-linear-regression}{%
\chapter{Real data example (Simple linear regression)}\label{real-data-example-simple-linear-regression}}

\hypertarget{read-the-data-into-the-r-studio-environment.}{%
\section{Read the data into the R Studio environment.}\label{read-the-data-into-the-r-studio-environment.}}

It also calcuates the covariance matrix among all the variables in the data.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dat <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"https://stats.idre.ucla.edu/wp-content/uploads/2021/02/worland5.csv"}\NormalTok{)}
\KeywordTok{cov}\NormalTok{(dat)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        motiv harm stabi ppsych ses verbal read arith spell
## motiv    100   77    59    -25  25     32   53    60    59
## harm      77  100    58    -25  26     25   42    44    45
## stabi     59   58   100    -16  18     27   36    38    38
## ppsych   -25  -25   -16    100 -42    -40  -39   -24   -31
## ses       25   26    18    -42 100     40   43    37    33
## verbal    32   25    27    -40  40    100   56    49    48
## read      53   42    36    -39  43     56  100    73    87
## arith     60   44    38    -24  37     49   73   100    72
## spell     59   45    38    -31  33     48   87    72   100
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{var}\NormalTok{(dat}\OperatorTok{$}\NormalTok{motiv)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 100
\end{verbatim}

In the following, we conduct a simple linear regression.
\[sample \ variance-covariance \ matrix \hat{\sum} = \mathbf{S} \]

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m1a <-}\StringTok{ }\KeywordTok{lm}\NormalTok{(read }\OperatorTok{~}\StringTok{ }\NormalTok{motiv, }\DataTypeTok{data=}\NormalTok{dat)}
\NormalTok{(fit1a <-}\KeywordTok{summary}\NormalTok{(m1a))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = read ~ motiv, data = dat)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -26.0995  -6.1109   0.2342   5.2237  24.0183 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(>|t|)    
## (Intercept) -1.232e-07  3.796e-01    0.00        1    
## motiv        5.300e-01  3.800e-02   13.95   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 8.488 on 498 degrees of freedom
## Multiple R-squared:  0.2809, Adjusted R-squared:  0.2795 
## F-statistic: 194.5 on 1 and 498 DF,  p-value: < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(lavaan)}
\CommentTok{#simple regression using lavaan }
\NormalTok{m1b <-}\StringTok{   '}
\StringTok{  # regressions}
\StringTok{    read ~ 1+ motiv}
\StringTok{  # variance (optional)}
\StringTok{    motiv ~~ motiv}
\StringTok{'}

\NormalTok{fit1b <-}\StringTok{ }\KeywordTok{sem}\NormalTok{(m1b, }\DataTypeTok{data=}\NormalTok{dat)}
\KeywordTok{summary}\NormalTok{(fit1b)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## lavaan 0.6-8 ended normally after 14 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                         5
##                                                       
##   Number of observations                           500
##                                                       
## Model Test User Model:
##                                                       
##   Test statistic                                 0.000
##   Degrees of freedom                                 0
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## Regressions:
##                    Estimate  Std.Err  z-value  P(>|z|)
##   read ~                                              
##     motiv             0.530    0.038   13.975    0.000
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(>|z|)
##    .read             -0.000    0.379   -0.000    1.000
##     motiv             0.000    0.447    0.000    1.000
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(>|z|)
##     motiv            99.800    6.312   15.811    0.000
##    .read             71.766    4.539   15.811    0.000
\end{verbatim}

\hypertarget{real-data-example-multiple-linear-regression}{%
\chapter{Real data example (Multiple linear regression)}\label{real-data-example-multiple-linear-regression}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m2 <-}\StringTok{ '}
\StringTok{  # regressions}
\StringTok{    read ~ 1 + ppsych + motiv}
\StringTok{ # covariance}
\StringTok{    ppsych ~~ motiv}
\StringTok{'}
\NormalTok{fit2 <-}\StringTok{ }\KeywordTok{sem}\NormalTok{(m2, }\DataTypeTok{data=}\NormalTok{dat)}
\KeywordTok{summary}\NormalTok{(fit2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## lavaan 0.6-8 ended normally after 34 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                         9
##                                                       
##   Number of observations                           500
##                                                       
## Model Test User Model:
##                                                       
##   Test statistic                                 0.000
##   Degrees of freedom                                 0
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## Regressions:
##                    Estimate  Std.Err  z-value  P(>|z|)
##   read ~                                              
##     ppsych           -0.275    0.037   -7.385    0.000
##     motiv             0.461    0.037   12.404    0.000
## 
## Covariances:
##                    Estimate  Std.Err  z-value  P(>|z|)
##   ppsych ~~                                           
##     motiv           -24.950    4.601   -5.423    0.000
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(>|z|)
##    .read              0.000    0.360    0.000    1.000
##     ppsych           -0.000    0.447   -0.000    1.000
##     motiv             0.000    0.447    0.000    1.000
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(>|z|)
##    .read             64.708    4.092   15.811    0.000
##     ppsych           99.800    6.312   15.811    0.000
##     motiv            99.800    6.312   15.811    0.000
\end{verbatim}

\hypertarget{bootstrapping}{%
\chapter{Bootstrapping}\label{bootstrapping}}

\hypertarget{warning}{%
\section{Warning}\label{warning}}

\textbf{Warning:}

\textbf{This page is for my own personal study purpose. Distribution is prohibited.}

\begin{center}\rule{0.5\linewidth}{\linethickness}\end{center}

\hypertarget{introduction}{%
\section{Introduction}\label{introduction}}

The following note is made when I was studying Bret Larget's note posted online.
\url{http://pages.stat.wisc.edu/~larget/stat302/chap3.pdf}

He used the data from LOck5data as an example.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(Lock5Data)}
\KeywordTok{data}\NormalTok{(CommuteAtlanta)}
\KeywordTok{str}\NormalTok{(CommuteAtlanta)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    500 obs. of  5 variables:
##  $ City    : Factor w/ 1 level "Atlanta": 1 1 1 1 1 1 1 1 1 1 ...
##  $ Age     : int  19 55 48 45 48 43 48 41 47 39 ...
##  $ Distance: int  10 45 12 4 15 33 15 4 25 1 ...
##  $ Time    : int  15 60 45 10 30 60 45 10 25 15 ...
##  $ Sex     : Factor w/ 2 levels "F","M": 2 2 2 1 1 2 2 1 2 1 ...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{time.mean =}\StringTok{ }\KeywordTok{with}\NormalTok{(CommuteAtlanta, }\KeywordTok{mean}\NormalTok{(Time))}

\NormalTok{time.mean}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 29.11
\end{verbatim}

Now, he sampled a (b X n) table. Note that, the Atlanta data has 500 row, as it has 500 observations (or, people). But, in the following new matrix, it is a (1000 times 500) table. Also, it should be noted that the logic of sample function in R. This webpage provides some insight into this function. Basically, the following R code randomly sample a bigger sample of (1000 times 500) from those 500 data points. After that, the matrix function put such (1000 times 500) data points into a matrix of (1000 times 500).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{B =}\StringTok{ }\DecValTok{1000}
\NormalTok{n =}\StringTok{ }\KeywordTok{nrow}\NormalTok{(CommuteAtlanta)}
\NormalTok{boot.samples =}\StringTok{ }\KeywordTok{matrix}\NormalTok{(}\KeywordTok{sample}\NormalTok{(CommuteAtlanta}\OperatorTok{$}\NormalTok{Time, }\DataTypeTok{size =}\NormalTok{ B }\OperatorTok{*}\StringTok{ }\NormalTok{n, }\DataTypeTok{replace =} \OtherTok{TRUE}\NormalTok{),}
\NormalTok{                      B, n)}
\end{Highlighting}
\end{Shaded}

Next, we need to calculate the mean for each row. Remember, we have 1000 rows. Note that, 1 in the apply function indicates that we calculate means on each row, whereas 2 indicates to each column.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{boot.statistics =}\StringTok{ }\KeywordTok{apply}\NormalTok{(boot.samples, }\DecValTok{1}\NormalTok{, mean)}
\end{Highlighting}
\end{Shaded}

We can then plot all the means.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{require}\NormalTok{(ggplot2)}
\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{meanTime =}\NormalTok{ boot.statistics),}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{meanTime)) }\OperatorTok{+}
\KeywordTok{geom_histogram}\NormalTok{(}\DataTypeTok{binwidth=}\FloatTok{0.25}\NormalTok{,}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{y=}\NormalTok{..density..)) }\OperatorTok{+}
\KeywordTok{geom_density}\NormalTok{(}\DataTypeTok{color=}\StringTok{"red"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-8-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{time.se =}\StringTok{ }\KeywordTok{sd}\NormalTok{(boot.statistics)}
\NormalTok{time.se}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.9243346
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{me =}\StringTok{ }\KeywordTok{ceiling}\NormalTok{(}\DecValTok{10} \OperatorTok{*}\StringTok{ }\DecValTok{2} \OperatorTok{*}\StringTok{ }\NormalTok{time.se)}\OperatorTok{/}\DecValTok{10}
\NormalTok{me}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.9
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{round}\NormalTok{(time.mean, }\DecValTok{1}\NormalTok{) }\OperatorTok{+}\StringTok{ }\KeywordTok{c}\NormalTok{(}\OperatorTok{-}\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{) }\OperatorTok{*}\StringTok{ }\NormalTok{me}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 27.2 31.0
\end{verbatim}

\hypertarget{normal-distribution-sd-se}{%
\section{Normal distribution, SD, SE}\label{normal-distribution-sd-se}}

Note, if we do not use bootstraping, we can use the standard CI formula (\url{https://www.mathsisfun.com/data/confidence-interval.html}). This formula assumes normal distribution. As we can see, this is close to the result based on the bootstrapping method.

\[\overline{X} \pm Z \frac{S}{\sqrt{n}}=29.11 \pm 1.96 \frac{20.72}{\sqrt{500}}=27.29, 30.93\]

Note that, in the following, the author used 2 times SE to calculate the CI. The relationship between SD and SE:

``Now the sample mean will vary from sample to sample; the way this variation occurs is described by the ``sampling distribution'' of the mean. We can estimate how much sample means will vary from the standard deviation of this sampling distribution, which we call the standard error (SE) of the estimate of the mean. As the standard error is a type of standard deviation, confusion is understandable. Another way of considering the standard error is as a measure of the precision of the sample mean." (\url{https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1255808/})

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{boot.mean =}\StringTok{ }\ControlFlowTok{function}\NormalTok{(x,B,}\DataTypeTok{binwidth=}\OtherTok{NULL}\NormalTok{)}
\NormalTok{\{}
\NormalTok{n =}\StringTok{ }\KeywordTok{length}\NormalTok{(x)}
\NormalTok{boot.samples =}\StringTok{ }\KeywordTok{matrix}\NormalTok{( }\KeywordTok{sample}\NormalTok{(x,}\DataTypeTok{size=}\NormalTok{n}\OperatorTok{*}\NormalTok{B,}\DataTypeTok{replace=}\OtherTok{TRUE}\NormalTok{), B, n)}
\NormalTok{boot.statistics =}\StringTok{ }\KeywordTok{apply}\NormalTok{(boot.samples,}\DecValTok{1}\NormalTok{,mean)}
\NormalTok{se =}\StringTok{ }\KeywordTok{sd}\NormalTok{(boot.statistics)}
\KeywordTok{require}\NormalTok{(ggplot2)}
\ControlFlowTok{if}\NormalTok{ ( }\KeywordTok{is.null}\NormalTok{(binwidth) )}
\NormalTok{binwidth =}\StringTok{ }\KeywordTok{diff}\NormalTok{(}\KeywordTok{range}\NormalTok{(boot.statistics))}\OperatorTok{/}\DecValTok{30}
\NormalTok{p =}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{x=}\NormalTok{boot.statistics),}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{x)) }\OperatorTok{+}
\KeywordTok{geom_histogram}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{y=}\NormalTok{..density..),}\DataTypeTok{binwidth=}\NormalTok{binwidth) }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_density}\NormalTok{(}\DataTypeTok{color=}\StringTok{"red"}\NormalTok{)}
\KeywordTok{plot}\NormalTok{(p)}
\NormalTok{interval =}\StringTok{ }\KeywordTok{mean}\NormalTok{(x) }\OperatorTok{+}\StringTok{ }\KeywordTok{c}\NormalTok{(}\OperatorTok{-}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{)}\OperatorTok{*}\DecValTok{2}\OperatorTok{*}\NormalTok{se}
\KeywordTok{print}\NormalTok{( interval )}
\KeywordTok{return}\NormalTok{( }\KeywordTok{list}\NormalTok{(}\DataTypeTok{boot.statistics =}\NormalTok{ boot.statistics, }\DataTypeTok{interval=}\NormalTok{interval, }\DataTypeTok{se=}\NormalTok{se, }\DataTypeTok{plot=}\NormalTok{p) )}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{out =}\StringTok{ }\KeywordTok{with}\NormalTok{(CommuteAtlanta, }\KeywordTok{boot.mean}\NormalTok{(Distance, }\DataTypeTok{B =} \DecValTok{1000}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-11-1.pdf}

\begin{verbatim}
## [1] 16.92365 19.38835
\end{verbatim}

\hypertarget{sample-function}{%
\section{Sample function}\label{sample-function}}

To understand the function of sample in R.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sample}\NormalTok{(}\DecValTok{20}\NormalTok{,}\DataTypeTok{replace =} \OtherTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] 16  4 11 19  9  7 15  7  2  2 10 10  6 17 13 17 15 18 17 11
\end{verbatim}

The following uses loop to do the resampling. It uses sample function to index the numbers that they want to sample from the original sample. That is, {[}{]} suggests the indexing.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n =}\StringTok{ }\KeywordTok{length}\NormalTok{(CommuteAtlanta}\OperatorTok{$}\NormalTok{Distance)}
\NormalTok{B =}\StringTok{ }\DecValTok{1000}
\NormalTok{result =}\StringTok{ }\KeywordTok{rep}\NormalTok{(}\OtherTok{NA}\NormalTok{, B)}
\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{1}\OperatorTok{:}\NormalTok{B)}
\NormalTok{\{}
\NormalTok{boot.sample =}\StringTok{ }\KeywordTok{sample}\NormalTok{(n, }\DataTypeTok{replace =} \OtherTok{TRUE}\NormalTok{)}
\NormalTok{result[i] =}\StringTok{ }\KeywordTok{mean}\NormalTok{(CommuteAtlanta}\OperatorTok{$}\NormalTok{Distance[boot.sample])}
\NormalTok{\}}

\KeywordTok{with}\NormalTok{(CommuteAtlanta, }\KeywordTok{mean}\NormalTok{(Distance) }\OperatorTok{+}\StringTok{ }\KeywordTok{c}\NormalTok{(}\OperatorTok{-}\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{) }\OperatorTok{*}\StringTok{ }\DecValTok{2} \OperatorTok{*}\StringTok{ }\KeywordTok{sd}\NormalTok{(result))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 16.92337 19.38863
\end{verbatim}

\hypertarget{proportion}{%
\section{Proportion}\label{proportion}}

So far, we have dealed with means. How about porpotions?Remember that, when calculating means, it starts with a single column of data to calculate the mean. Similarly, when calculating porpotions, you can just use a single column of data.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{reeses =}\StringTok{ }\KeywordTok{c}\NormalTok{(}\KeywordTok{rep}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{11}\NormalTok{), }\KeywordTok{rep}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{19}\NormalTok{))}
\NormalTok{reeses.boot =}\StringTok{ }\KeywordTok{boot.mean}\NormalTok{(reeses, }\DecValTok{1000}\NormalTok{, }\DataTypeTok{binwidth =} \DecValTok{1}\OperatorTok{/}\DecValTok{30}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-14-1.pdf}

\begin{verbatim}
## [1] 0.1889370 0.5443964
\end{verbatim}

However, if we have 48 students (i.e., 48 observations) and thus we have a bigger sample. However, how can we do re-sampling? Based on the note, it is kind of simple. They group them together and then resample from it. Note that, when they re-sampling, the programming do not distinguish the difference between 48 observations. But just combined them as a single column (741+699=1440), and then generate a very long column (1440 times 1000) and then reshape it into a matrix (1440 time 1000). This is the basic logic of the boot.mean function.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{reeses =}\StringTok{ }\KeywordTok{c}\NormalTok{(}\KeywordTok{rep}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{741}\NormalTok{), }\KeywordTok{rep}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{699}\NormalTok{))}
\NormalTok{reeses.boot =}\StringTok{ }\KeywordTok{boot.mean}\NormalTok{(reeses, }\DecValTok{1000}\NormalTok{, }\DataTypeTok{binwidth =} \FloatTok{0.005}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-15-1.pdf}

\begin{verbatim}
## [1] 0.4873028 0.5418639
\end{verbatim}

\hypertarget{boot-package}{%
\section{boot package}\label{boot-package}}

After having a basic idea of boostrapping, we can then use the package of boot.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(boot)}

\KeywordTok{data}\NormalTok{(CommuteAtlanta)}

\NormalTok{my.mean =}\StringTok{ }\ControlFlowTok{function}\NormalTok{(x, indices)}
\NormalTok{\{}
\KeywordTok{return}\NormalTok{( }\KeywordTok{mean}\NormalTok{( x[indices] ) )}
\NormalTok{\}}

\NormalTok{time.boot =}\StringTok{ }\KeywordTok{boot}\NormalTok{(CommuteAtlanta}\OperatorTok{$}\NormalTok{Time, my.mean, }\DecValTok{10000}\NormalTok{)}

\KeywordTok{boot.ci}\NormalTok{(time.boot)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in boot.ci(time.boot): bootstrap variances needed for studentized
## intervals
\end{verbatim}

\begin{verbatim}
## BOOTSTRAP CONFIDENCE INTERVAL CALCULATIONS
## Based on 10000 bootstrap replicates
## 
## CALL : 
## boot.ci(boot.out = time.boot)
## 
## Intervals : 
## Level      Normal              Basic         
## 95%   (27.26, 30.93 )   (27.23, 30.84 )  
## 
## Level     Percentile            BCa          
## 95%   (27.38, 30.99 )   (27.44, 31.10 )  
## Calculations and Intervals on Original Scale
\end{verbatim}

\hypertarget{concept-of-percentile}{%
\section{Concept of Percentile}\label{concept-of-percentile}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{require}\NormalTok{(Lock5Data)}
\KeywordTok{data}\NormalTok{(ImmuneTea)}
\NormalTok{tea =}\StringTok{ }\KeywordTok{with}\NormalTok{(ImmuneTea, InterferonGamma[Drink}\OperatorTok{==}\StringTok{"Tea"}\NormalTok{])}
\NormalTok{coffee =}\StringTok{ }\KeywordTok{with}\NormalTok{(ImmuneTea, InterferonGamma[Drink}\OperatorTok{==}\StringTok{"Coffee"}\NormalTok{])}
\NormalTok{tea.mean =}\StringTok{ }\KeywordTok{mean}\NormalTok{(tea)}
\NormalTok{coffee.mean =}\StringTok{ }\KeywordTok{mean}\NormalTok{(coffee)}
\NormalTok{tea.n =}\StringTok{ }\KeywordTok{length}\NormalTok{(tea)}
\NormalTok{coffee.n =}\StringTok{ }\KeywordTok{length}\NormalTok{(coffee)}



\NormalTok{B =}\StringTok{ }\DecValTok{500}
\CommentTok{# create empty arrays for the means of each sample}
\NormalTok{tea.boot =}\StringTok{ }\KeywordTok{numeric}\NormalTok{(B)}
\NormalTok{coffee.boot =}\StringTok{ }\KeywordTok{numeric}\NormalTok{(B)}
\CommentTok{# Use a for loop to take the samples}
\ControlFlowTok{for}\NormalTok{ ( i }\ControlFlowTok{in} \DecValTok{1}\OperatorTok{:}\NormalTok{B )}
\NormalTok{  \{}
\NormalTok{tea.boot[i] =}\StringTok{ }\KeywordTok{mean}\NormalTok{(}\KeywordTok{sample}\NormalTok{(tea,}\DataTypeTok{size=}\NormalTok{tea.n,}\DataTypeTok{replace=}\OtherTok{TRUE}\NormalTok{))}
\NormalTok{coffee.boot[i] =}\StringTok{ }\KeywordTok{mean}\NormalTok{(}\KeywordTok{sample}\NormalTok{(coffee,}\DataTypeTok{size=}\NormalTok{coffee.n,}\DataTypeTok{replace=}\OtherTok{TRUE}\NormalTok{))}
\NormalTok{\}}

\NormalTok{boot.stat =}\StringTok{ }\NormalTok{tea.boot }\OperatorTok{-}\StringTok{ }\NormalTok{coffee.boot}
\NormalTok{boot.stat}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   [1] 22.0545455 26.2818182 25.9000000 32.1636364 20.1636364  7.4454545
##   [7] 23.4181818 19.9727273  6.0454545 14.6090909  5.0454545 37.4545455
##  [13]  5.6818182  5.1636364 22.0181818 11.0727273 15.6727273  9.8818182
##  [19] 14.7272727  2.9272727 17.5545455  8.7636364 16.5727273 15.7909091
##  [25] 14.0818182 22.8727273 20.3545455 17.3363636 20.5181818 11.8545455
##  [31] 16.9727273  5.4818182 26.0090909 21.7454545 23.4545455  5.7454545
##  [37] 11.0818182  3.8636364 24.0909091 32.5727273  3.2545455  2.1636364
##  [43] 20.7454545 22.0272727 19.1272727 14.7727273  3.7636364 10.1818182
##  [49] 20.1545455 12.1090909 -0.5727273 11.1363636 12.0636364 21.9818182
##  [55] 11.3818182 11.3818182  5.8272727 27.3727273 15.8363636  8.7727273
##  [61] 10.4181818 16.9636364 30.8909091 27.6090909 21.9272727 13.5090909
##  [67] 13.4363636  3.3818182 26.5272727 11.2181818 21.1000000 33.5454545
##  [73] 21.2727273 20.0363636 25.0090909 13.4727273 12.7636364 18.3090909
##  [79] 16.8636364 10.8454545 17.4909091  3.4272727 11.9636364 13.8272727
##  [85]  9.8454545  4.3545455 26.8363636  9.9909091 32.6000000  6.4272727
##  [91] 12.7181818 24.5181818 14.1272727 25.9818182 26.9727273 14.8181818
##  [97] 20.5909091 12.5545455 24.5545455 23.3727273  9.6090909 18.5272727
## [103] 21.3000000 11.5090909 24.3363636 21.8636364 25.1545455 20.3727273
## [109] 14.0818182  8.5000000 11.8272727 25.0272727  5.6818182 15.4272727
## [115]  8.6909091 21.2181818 22.9636364 21.5181818 12.8454545 17.8090909
## [121] 17.9090909  6.0363636 17.8363636 10.7545455 18.0545455 18.9636364
## [127] 13.4272727  8.3272727 13.9090909  7.0363636  6.0000000 19.9272727
## [133] 24.2909091 21.6727273 18.6363636 22.3909091 24.9000000  9.4272727
## [139] 25.2272727  9.8272727 15.8181818 19.3181818 27.9000000  8.8181818
## [145]  9.6090909 30.4000000 13.9818182 10.6727273 27.0363636 10.7545455
## [151] 21.8000000 20.7818182 10.4363636 23.3000000 24.6090909 15.8636364
## [157] 17.8545455 12.1181818 17.7545455  7.3727273  4.7818182 22.7363636
## [163] 16.1181818 13.6727273 12.5090909 17.4545455 22.0090909 13.5090909
## [169] 11.6181818 10.4000000 -2.4272727 18.4545455  6.8272727 14.4272727
## [175] 20.5454545  7.0090909 17.4363636 13.6818182 16.2545455 20.5636364
## [181] -0.1818182  8.9272727 21.3272727 12.1818182  6.4272727 21.3818182
## [187] 11.9000000 20.7545455 14.3909091  1.6454545 22.6272727 17.1454545
## [193] 19.0090909 -3.9363636 22.3545455 14.7363636  4.9545455 19.5909091
## [199] 15.0727273  0.3090909 13.6727273 11.4727273 17.1727273 16.2000000
## [205] 18.7000000 15.1272727 32.6727273 20.3727273 21.8909091 24.8727273
## [211] 18.0000000 12.5454545 14.4181818 14.2545455 25.6727273  1.7181818
## [217] 18.5818182 16.9727273  6.7363636 33.9181818 27.7636364 14.9727273
## [223] 12.0181818 20.5272727 26.7090909  9.7909091 17.1909091 12.8090909
## [229] 18.4272727 12.8454545 27.3181818 26.3000000 16.7636364 13.3090909
## [235] 15.0181818  7.8272727 14.8363636 18.9181818 17.6636364 10.5363636
## [241]  4.6727273 16.8000000 28.5090909 25.2090909 27.1818182 25.2181818
## [247]  5.3727273 20.1363636 18.3181818 13.5181818 28.4909091 10.6090909
## [253] 12.2272727 15.1818182 25.9272727  9.3909091 15.2727273  8.1000000
## [259]  9.1272727 14.3727273 -1.1909091 25.1727273  5.5272727 26.3545455
## [265]  7.0000000 19.8272727 37.1636364 14.6181818 12.9000000 19.7181818
## [271] 23.1363636 17.3636364 27.4454545 34.1181818 39.5636364 24.9000000
## [277] 25.2363636 32.8363636 10.9363636 20.4818182 17.9272727 23.3636364
## [283] 18.3545455 12.4363636 10.0000000  5.0636364 19.6181818 28.7727273
## [289]  9.6727273 26.9909091  3.7636364  8.6090909 13.6909091  3.4272727
## [295] 20.9000000 22.4000000 13.3363636 27.0545455 17.4090909 13.0727273
## [301] 19.4272727 14.5909091 16.5909091 19.7818182 18.2636364  6.6818182
## [307] 22.0363636 17.7272727 18.5454545 20.4545455 26.5181818 17.1909091
## [313] 11.1000000 -1.3818182 11.8181818  4.1636364 26.2818182 24.5363636
## [319] 12.2090909  7.5909091 28.6727273 19.7090909 20.6181818  5.0727273
## [325] 18.3000000 19.3454545  7.9272727 18.5636364 10.7909091 11.4272727
## [331] 20.6181818  9.4454545 31.2727273 23.4454545 23.7000000 18.5272727
## [337] 12.1818182 11.4272727 11.3818182 18.4000000 11.6000000 17.9636364
## [343] 17.2454545 23.5545455 17.7454545 12.6181818 13.3818182 12.9454545
## [349] 21.7363636 21.9000000 17.1272727  5.1545455 17.0181818 20.5545455
## [355] 29.9454545 18.4454545 17.1000000 19.5454545 17.4818182 21.8909091
## [361]  2.1454545 25.0454545  7.4454545 25.0909091 14.9454545 31.8000000
## [367] 25.5272727 15.6909091 10.4909091 25.5909091 11.3909091 12.6272727
## [373]  7.3636364 26.1000000 13.8000000 32.3090909 15.3090909  3.5727273
## [379] 22.9545455  3.5636364 32.2454545 14.1636364 16.4272727 29.7454545
## [385] 13.1272727  9.5545455 -2.3636364 27.7727273 12.3000000 11.9727273
## [391] 17.8090909 13.9727273 17.8090909 22.7363636 21.8000000 10.6545455
## [397] 19.5636364 20.8727273 25.2818182 14.0545455 20.1545455 23.0454545
## [403] 11.9454545  6.5454545 10.8909091 13.6454545 19.3636364 26.0454545
## [409] 25.2000000 17.5272727 12.3272727 25.8181818 26.3909091  2.8636364
## [415] 16.7636364 18.7727273 27.1454545 20.3181818 13.8727273 19.8090909
## [421] 14.9363636 21.1000000  9.3090909 15.1818182 23.1545455 24.7454545
## [427] 15.1363636 11.6727273 17.0727273  2.4818182 10.5636364 10.4727273
## [433] 15.2818182 24.0818182  9.3818182 23.7272727 31.6000000  6.4000000
## [439] 18.1636364  0.2545455 20.3454545 19.8727273 -1.1727273 11.9000000
## [445] 32.9090909 15.7000000 16.3363636 25.7454545 21.2090909  9.3090909
## [451] 13.9545455 23.8454545 10.0363636 32.3727273 20.6727273 25.2272727
## [457] 27.2545455 17.1545455 19.5454545 -0.1000000  4.2545455 13.7636364
## [463] 34.7272727  6.7818182 19.0090909 10.0636364  8.7909091 16.2727273
## [469] 24.2090909 12.2363636 36.9090909  7.0818182 31.4545455 25.5000000
## [475] 11.7454545 24.0909091 11.0272727 11.4636364 12.0818182  4.8818182
## [481]  6.7181818 16.3363636 14.2090909 16.0818182 24.6545455 12.5090909
## [487] 16.3090909 19.5818182  0.1909091  3.3454545 18.0363636 29.9000000
## [493] 25.6727273 18.7090909 15.0090909 11.2272727 15.8090909  7.7363636
## [499] 27.8545455 22.9181818
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Find endpoints for 90%, 95%, and 99% bootstrap confidence intervals using percentiles.}

\CommentTok{# 90%:  5% 95%}
\KeywordTok{quantile}\NormalTok{(boot.stat,}\KeywordTok{c}\NormalTok{(}\FloatTok{0.05}\NormalTok{,}\FloatTok{0.95}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        5%       95% 
##  3.572273 29.753182
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# 95%: 2.5% 97.5%}
\KeywordTok{quantile}\NormalTok{(boot.stat,}\KeywordTok{c}\NormalTok{(}\FloatTok{0.025}\NormalTok{,}\FloatTok{0.975}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     2.5%    97.5% 
##  1.68000 32.47773
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# 99%:  0.5% 99.5%}
\KeywordTok{quantile}\NormalTok{(boot.stat,}\KeywordTok{c}\NormalTok{(}\FloatTok{0.005}\NormalTok{,}\FloatTok{0.995}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      0.5%     99.5% 
## -1.877636 37.037636
\end{verbatim}

\hypertarget{bootstrapping-for-correlation-interval}{%
\section{Bootstrapping for correlation interval}\label{bootstrapping-for-correlation-interval}}

Some data and code are from: \url{https://blog.methodsconsultants.com/posts/understanding-bootstrap-confidence-interval-output-from-the-r-boot-package/}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data_correlation<-}\KeywordTok{read.csv}\NormalTok{(}\StringTok{"data_correlation.csv"}\NormalTok{,}\DataTypeTok{fileEncoding=}\StringTok{"UTF-8-BOM"}\NormalTok{)}

\NormalTok{data_correlation}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Student LSAT  GPA
## 1        1  576 3.39
## 2        2  635 3.30
## 3        3  558 2.81
## 4        4  578 3.03
## 5        5  666 3.44
## 6        6  580 3.07
## 7        7  555 3.00
## 8        8  661 3.43
## 9        9  651 3.36
## 10      10  605 3.13
## 11      11  653 3.12
## 12      12  575 2.74
## 13      13  545 2.76
## 14      14  572 2.88
## 15      15  594 2.96
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{cor.test}\NormalTok{(data_correlation}\OperatorTok{$}\NormalTok{LSAT,data_correlation}\OperatorTok{$}\NormalTok{GPA)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Pearson's product-moment correlation
## 
## data:  data_correlation$LSAT and data_correlation$GPA
## t = 4.4413, df = 13, p-value = 0.0006651
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.4385108 0.9219648
## sample estimates:
##       cor 
## 0.7763745
\end{verbatim}

In the following, I will write my own code to execute the bootstrapping. I set the bootstrapping number only 500, for illustrative purposes. As we can see, the distribution is not symmetrical.

As we can see, the quantile result and c(-1, 1) X 2 are not the same, as the latter assumes symmetrical distribution. However, based on the histogram, we know it is not the case. Thus, quantile would be more appropriate. You can compare the result with that from the boot function.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n_row =}\StringTok{ }\KeywordTok{nrow}\NormalTok{(data_correlation)}
\NormalTok{n_row}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 15
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{set.seed}\NormalTok{(}\DecValTok{12345}\NormalTok{)}

\NormalTok{B =}\StringTok{ }\DecValTok{500}
\NormalTok{result =}\StringTok{ }\KeywordTok{rep}\NormalTok{(}\OtherTok{NA}\NormalTok{, B)}
\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{1}\OperatorTok{:}\NormalTok{B)}
\NormalTok{\{}
\NormalTok{boot.sample =}\StringTok{ }\KeywordTok{sample}\NormalTok{(n_row, }\DataTypeTok{replace =} \OtherTok{TRUE}\NormalTok{)}
\NormalTok{result_temp =}\StringTok{ }\KeywordTok{cor.test}\NormalTok{(data_correlation[boot.sample,]}\OperatorTok{$}\NormalTok{LSAT,data_correlation[boot.sample,]}\OperatorTok{$}\NormalTok{GPA)}
\NormalTok{result[i]=result_temp}\OperatorTok{$}\NormalTok{estimate}
\NormalTok{\}}
\KeywordTok{hist}\NormalTok{(result)}
\end{Highlighting}
\end{Shaded}

\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-20-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# 95%: 2.5% 97.5%}
\KeywordTok{quantile}\NormalTok{(result,}\KeywordTok{c}\NormalTok{(}\FloatTok{0.025}\NormalTok{,}\FloatTok{0.975}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      2.5%     97.5% 
## 0.4369293 0.9556859
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sd}\NormalTok{(result)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.1342631
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{mean}\NormalTok{(result) }\OperatorTok{+}\StringTok{ }\KeywordTok{c}\NormalTok{(}\OperatorTok{-}\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{) }\OperatorTok{*}\StringTok{ }\FloatTok{1.96} \OperatorTok{*}\StringTok{ }\KeywordTok{sd}\NormalTok{(result)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.5107704 1.0370816
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{cor}\NormalTok{(data_correlation}\OperatorTok{$}\NormalTok{LSAT,data_correlation}\OperatorTok{$}\NormalTok{GPA)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.7763745
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{cor}\NormalTok{(data_correlation}\OperatorTok{$}\NormalTok{LSAT,data_correlation}\OperatorTok{$}\NormalTok{GPA)}\OperatorTok{+}\StringTok{ }\KeywordTok{c}\NormalTok{(}\OperatorTok{-}\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{) }\OperatorTok{*}\StringTok{ }\FloatTok{1.96} \OperatorTok{*}\StringTok{ }\KeywordTok{sd}\NormalTok{(result)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.5132189 1.0395301
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# why add 0.005? Not sure. The following is from the webpage. Later note: please refer to the webpage, as it provides the logic of basic interval.}

\FloatTok{0.776+0.005}\OperatorTok{+}\KeywordTok{c}\NormalTok{(}\OperatorTok{-}\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{) }\OperatorTok{*}\StringTok{ }\FloatTok{1.96} \OperatorTok{*}\StringTok{ }\FloatTok{0.131}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.52424 1.03776
\end{verbatim}

In the blog mentioned above, the author used the boot function in R. For the logic of basic interval, please refer to:
\url{https://blog.methodsconsultants.com/posts/understanding-bootstrap-confidence-interval-output-from-the-r-boot-package/}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(boot)}

\NormalTok{get_r <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(data, indices, x, y) \{}
\NormalTok{  d <-}\StringTok{ }\NormalTok{data[indices, ]}
\NormalTok{  r <-}\StringTok{ }\KeywordTok{round}\NormalTok{(}\KeywordTok{as.numeric}\NormalTok{(}\KeywordTok{cor}\NormalTok{(d[x], d[y])), }\DecValTok{3}\NormalTok{)}
\NormalTok{  r\}}

\KeywordTok{set.seed}\NormalTok{(}\DecValTok{12345}\NormalTok{)}

\NormalTok{boot_out <-}\StringTok{ }\KeywordTok{boot}\NormalTok{(}
\NormalTok{  data_correlation,}
  \DataTypeTok{x =} \StringTok{"LSAT"}\NormalTok{, }
  \DataTypeTok{y =} \StringTok{"GPA"}\NormalTok{, }
  \DataTypeTok{R =} \DecValTok{500}\NormalTok{,}
  \DataTypeTok{statistic =}\NormalTok{ get_r}
\NormalTok{)}

\KeywordTok{boot.ci}\NormalTok{(boot_out)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in boot.ci(boot_out): bootstrap variances needed for studentized
## intervals
\end{verbatim}

\begin{verbatim}
## BOOTSTRAP CONFIDENCE INTERVAL CALCULATIONS
## Based on 500 bootstrap replicates
## 
## CALL : 
## boot.ci(boot.out = boot_out)
## 
## Intervals : 
## Level      Normal              Basic         
## 95%   ( 0.5247,  1.0368 )   ( 0.5900,  1.0911 )  
## 
## Level     Percentile            BCa          
## 95%   ( 0.4609,  0.9620 )   ( 0.3948,  0.9443 )  
## Calculations and Intervals on Original Scale
## Some BCa intervals may be unstable
\end{verbatim}

\hypertarget{poisson-regression}{%
\chapter{Poisson Regression}\label{poisson-regression}}

\hypertarget{basic-idea}{%
\section{Basic idea}\label{basic-idea}}

The following is based on the lecture note of \url{https://bookdown.org/roback/bookdown-BeyondMLR/ch-poissonreg.html}

There is also some R code related to this.

\url{https://rdrr.io/github/sta303-bolton/sta303w8/f/inst/rmarkdown/templates/philippines/skeleton/skeleton.Rmd}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fHH1 <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"https://raw.githubusercontent.com/proback/BeyondMLR/master/data/fHH1.csv"}\NormalTok{)}

\KeywordTok{head}\NormalTok{(fHH1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   X     location age total numLT5                          roof
## 1 1 CentralLuzon  65     0      0 Predominantly Strong Material
## 2 2  MetroManila  75     3      0 Predominantly Strong Material
## 3 3  DavaoRegion  54     4      0 Predominantly Strong Material
## 4 4      Visayas  49     3      0 Predominantly Strong Material
## 5 5  MetroManila  74     3      0 Predominantly Strong Material
## 6 6      Visayas  59     6      0 Predominantly Strong Material
\end{verbatim}

\[log (\lambda_X) =\beta_0+\beta_1 X\]
\[log (\lambda_{X+1}) =\beta_0+\beta_1 (X+1)\]

Thus,

\[log (\lambda_{X+1})-log (\lambda_X) =(\beta_0+\beta_1 (X+1))-(\beta_0+\beta_1 X)\]

Thus,

\[log (\frac{\lambda_{X+1}}{\lambda_X}) =\beta_1\]

Thus,

\[\frac{\lambda_{X+1}}{\lambda_X} =e^{\beta_1}\]

Note that, \(\lambda\) here is the mean. It is poisson regression, and the parameter is the mean. Thus, \(\frac{\lambda_{X+1}}{\lambda_X} =e^{\beta_1}\) suggests the ratio change in the DV as the IV change in one unit.

\[log (\hat{\lambda}) =b_0+b_1 Age\]

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{result_}\DecValTok{1}\NormalTok{ =}\StringTok{ }\KeywordTok{glm}\NormalTok{(total }\OperatorTok{~}\StringTok{ }\NormalTok{age, }\DataTypeTok{family =}\NormalTok{ poisson, }\DataTypeTok{data =}\NormalTok{ fHH1)}
\KeywordTok{summary}\NormalTok{(result_}\DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## glm(formula = total ~ age, family = poisson, data = fHH1)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.9079  -0.9637  -0.2155   0.6092   4.9561  
## 
## Coefficients:
##               Estimate Std. Error z value Pr(>|z|)    
## (Intercept)  1.5499422  0.0502754  30.829  < 2e-16 ***
## age         -0.0047059  0.0009363  -5.026 5.01e-07 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 2362.5  on 1499  degrees of freedom
## Residual deviance: 2337.1  on 1498  degrees of freedom
## AIC: 6714
## 
## Number of Fisher Scoring iterations: 5
\end{verbatim}

\[\frac{\lambda_{Age+1}}{\lambda_{Age}} =e^{\beta_1}=e^{-0.0047}=0.995\]

But, what does it mean? It is a bit tricky. But, we can make some modification to help us understand.

\[\lambda_{Age+1} =0.995 \lambda_{Age}\]
\[\lambda_{Age+1} - \lambda_{Age}=0.995 \lambda_{Age}- \lambda_{Age}=-0.005 \lambda_{Age}\]
Thus, we can understand that, the difference in the household size mean by changing 1 unit of age (i.e., \(\lambda_{Age+1} - \lambda_{Age}\)) is \(-0.005 \lambda_{Age}\).

That is, the difference in the household size mean by changing 1 unit of age (i.e., \(\lambda_{Age+1} - \lambda_{Age}\)) is a decrease of 5\% of \(\lambda_{Age}\).

We can then calculate the confidence interval.

\[(\hat{\beta_1}-Z*SE(\hat{\beta_1}), \hat{\beta_1}+Z*SE(\hat{\beta_1}))\]

\[(-0.0047-1.96*0.00094,-0.0047+1.96*0.00094)=(−0.0065,−0.0029)\]

We can then plug them back to the exponential.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{exp}\NormalTok{(−}\FloatTok{0.0065}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.9935211
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{exp}\NormalTok{(−}\FloatTok{0.0029}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.9971042
\end{verbatim}

\[(e^{−0.0065},e^{−0.0029})=(0.9935,0.9971)\]

You can also get the confidence interval directly use R code

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{confint}\NormalTok{(result_}\DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Waiting for profiling to be done...
\end{verbatim}

\begin{verbatim}
##                    2.5 %       97.5 %
## (Intercept)  1.451170100  1.648249185
## age         -0.006543163 -0.002872717
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{exp}\NormalTok{(}\KeywordTok{confint}\NormalTok{(result_}\DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Waiting for profiling to be done...
\end{verbatim}

\begin{verbatim}
##                 2.5 %    97.5 %
## (Intercept) 4.2681057 5.1978713
## age         0.9934782 0.9971314
\end{verbatim}

Note that, we use original beta to construct a confidence interval and then exponentiate the endpoints is due to the fact that the oringal one is more close to normal distribution.

\hypertarget{trying-to-understand}{%
\section{Trying to understand}\label{trying-to-understand}}

With \(\hat{\beta_0} = 1.55\) and \(\hat{\beta_1}=-0.005\), we can write down the following. I also simulated the data and showed the relationship between X and Y. As we can see the figure, the relationship is pretty linear. Thus, something to keep in mind, the poisson distribution we typically see is the histogram of Y, rather than the relationship between X and Y.

\[log(\hat{\lambda})=1.55-0.005 Age\]

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data_age<-}\KeywordTok{seq}\NormalTok{(}\DecValTok{20}\NormalTok{,}\DecValTok{100}\NormalTok{,}\FloatTok{0.5}\NormalTok{)}
\NormalTok{f_age<-}\ControlFlowTok{function}\NormalTok{(x)\{}\KeywordTok{exp}\NormalTok{(}\FloatTok{1.55}\OperatorTok{-}\NormalTok{(}\FloatTok{0.005}\OperatorTok{*}\NormalTok{x))\}}
\CommentTok{# cbind(data_age,f_age(data_age))}
\KeywordTok{plot}\NormalTok{(data_age,}\KeywordTok{f_age}\NormalTok{(data_age))}
\end{Highlighting}
\end{Shaded}

\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-26-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{hist}\NormalTok{(}\KeywordTok{f_age}\NormalTok{(data_age))}
\end{Highlighting}
\end{Shaded}

\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-26-2.pdf}

\hypertarget{use-r-for-mediation}{%
\chapter{Use R for mediation}\label{use-r-for-mediation}}

\url{https://advstats.psychstat.org/book/mediation/index.php}

\bibliography{book.bib,packages.bib}


\end{document}
